-- AlterTable
ALTER TABLE "Pet" ALTER COLUMN "hunger" SET DEFAULT 100,
ALTER COLUMN "hunger" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "thirst" SET DEFAULT 100,
ALTER COLUMN "thirst" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "cleanliness" SET DEFAULT 100,
ALTER COLUMN "cleanliness" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "fatigue" SET DEFAULT 0,
ALTER COLUMN "fatigue" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "health" SET DEFAULT 100,
ALTER COLUMN "health" SET DATA TYPE DOUBLE PRECISION;
